// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddsdidxdwdbqdoyczhyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkc2RpZHhkd2RicWRveWN6aHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTQ5NzMsImV4cCI6MjA1ODA5MDk3M30.qZbZVEltkvHgX6YHd61GffYLRChXzygeSP8rp-usNT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);